# Simple Pipeline Configuration - Two Agent Pipeline

# Provider configuration
provider: "gemini"
model: "gemini-2.5-flash"
api_key: "${GEMINI_API_KEY}"

# Dataset defaults
data:
  prompt: |
    Find the outstanding papers of ACL 2025, extract their title, author list, keywords, abstract, url in one sentence.

# Pipeline settings
pipeline:
  verbose: true

# Agent profiles
agents:
  routing_agent:
    profile: routing_agent_simple

  web_searcher_agent:
    profile: web_searcher
