# Simple Pipeline Configuration - Two Agent Pipeline

# Provider configuration
provider: "gemini"
model: "gemini-2.5-flash"
api_key: "${GEMINI_API_KEY}"


prompt: |
  - Open google.com
  - Search for which LPL team loses to Vietnam in Bo3
  - Return the name of that team

# Pipeline settings
pipeline:
  verbose: true

# Agent instructions
agents:
  routing_agent:
    instructions: |
      You are a task routing agent. Analyze the user query and create a task for the browser_agent.

      The browser_agent can:
      - Open a website
      - Search the web
      - Click on links
      - Read the content of the page
      - Click on buttons
      - Fill out forms
      - Submit forms

      Create a clear, specific task with:
      - agent: "browser_agent"
      - query: detailed task description
      - gap: the knowledge gap being addressed
      
  browser_agent:
    instructions: |
      You are a browser agent. Interact with the browser MCP Server following the instructions provided to complete the task.
