[project]
name = "ds1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "litellm==1.76",
    "loguru>=0.7.3",
    "openai-agents>=0.3.2",
    "rich>=14.1.0",
    "weave>=0.52.8",
]
